---
- name: Get list of upgradeable packages on Debian-based systems
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Execute apt list --upgradable
      ansible.builtin.shell: apt list --upgradable 2>/dev/null
      register: upgradeable_packages_output

    - name: Count the number of upgradeable packages
      ansible.builtin.shell: "echo '{{ upgradeable_packages_output.stdout }}' | grep -v '^Listing' | wc -l"
      register: upgradeable_packages_output_count

    - name: Append upgradeable packages count to CSV file
      delegate_to: localhost
      ansible.builtin.lineinfile:
        path: "{{ playbook_dir }}/list.csv"
        line: "{{ ansible_default_ipv4.address }}, {{ upgradeable_packages_output_count.stdout }}, {{ ansible_default_ipv4.address | regex_replace('\\.', '-') }}.csv"
        create: yes
        state: present

    - name: Save output to CSV file
      delegate_to: localhost
      ansible.builtin.copy:
        content: |
          Host,Package
          {{ ansible_default_ipv4.address }},{{ upgradeable_packages_output.stdout | regex_replace('\n', '\n' + ansible_default_ipv4.address + '\t') }}
        dest: "{{ playbook_dir }}/files/{{ ansible_default_ipv4.address | regex_replace('\\.', '-') }}.csv"
